name: mkcchoirlyrics
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.8+23

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share_plus: ^11.0.0
  path_provider: 2.1.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  change_app_package_name: ^1.4.0
  google_nav_bar: ^5.0.5
  flutter_email_sender: ^6.0.2
  line_awesome_flutter: ^2.0.0
  settings_ui: ^2.0.2
  rating_dialog: ^2.0.3
  in_app_review: 2.0.9
  provider: ^6.0.0
  rflutter_alert: ^2.0.7
  url_launcher: 6.2.5
  #  flutter_inappwebview: ^6.0.0
  carousel_slider: ^5.0.0
  shared_preferences: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.1.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/main_icon.png"
  image_path_ios: "assets/images/main_icon.png"
  image_path_android: "assets/images/main_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/mkcc_icon_foreground.png"
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/album_names.json
    - assets/languages_song.json
    - assets/album_songs.json
    - assets/all_songs.json
    - assets/images/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abyssinica
      fonts:
        - asset: assets/abyssinica.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
